import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useProjectsStore, emptySnapshot } from "../../store/projectsStore.js";
export function LandingPage({ onEnterApp, onOpenProjects }) {
    const [naming, setNaming] = useState(false);
    const [projectName, setProjectName] = useState("");
    const { createProject, projects } = useProjectsStore();
    function handleCreate() {
        const name = projectName.trim() || "Untitled Project";
        const localId = createProject(name, emptySnapshot());
        setNaming(false);
        setProjectName("");
        // Push to server in background so the project gets an apiId
        useProjectsStore.getState().pushToServer(localId);
        onEnterApp();
    }
    return (_jsxs("div", { className: "relative w-full h-full overflow-hidden", style: { background: "#080612" }, children: [_jsx("img", { src: "/HERO.png", alt: "", "aria-hidden": true, className: "absolute inset-0 w-full h-full object-cover" }), _jsx("div", { className: "absolute inset-0", style: { background: "linear-gradient(to bottom, rgba(8,6,18,0.45) 0%, rgba(8,6,18,0.35) 35%, rgba(8,6,18,0.65) 70%, rgba(8,6,18,0.92) 100%)" } }), _jsx("div", { className: "absolute inset-0 pointer-events-none", style: { background: "radial-gradient(ellipse 80% 60% at 50% -10%, rgba(109,40,217,0.35) 0%, transparent 70%), radial-gradient(ellipse 50% 40% at 80% 80%, rgba(59,7,100,0.25) 0%, transparent 70%)" } }), _jsxs("div", { className: "relative z-10 flex flex-col items-center justify-center h-full px-8 gap-8", children: [_jsxs("div", { className: "flex flex-col items-center gap-2", children: [_jsx("h1", { className: "text-7xl font-black tracking-[0.25em] text-white uppercase", style: { textShadow: "0 0 60px rgba(139,92,246,0.6), 0 2px 4px rgba(0,0,0,0.8)" }, children: "VIGO" }), _jsx("p", { className: "text-base font-medium tracking-[0.15em] uppercase text-[#9b93ba]", children: "Project Estimation Suite" })] }), _jsxs("p", { className: "text-xl text-[#c5bedf] font-light text-center max-w-md", style: { textShadow: "0 1px 8px rgba(0,0,0,0.6)" }, children: ["From post-its to production schedules,", _jsx("br", {}), "all in one place."] }), !naming ? (_jsxs("div", { className: "flex flex-col sm:flex-row items-center gap-4", children: [_jsxs("button", { onClick: () => setNaming(true), className: "group relative px-10 py-4 rounded-2xl text-lg font-semibold text-white transition-all duration-200 overflow-hidden", style: { background: "linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)", boxShadow: "0 0 32px rgba(124,58,237,0.5), 0 4px 16px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.1)", minWidth: 220 }, children: [_jsxs("span", { className: "relative z-10 flex items-center justify-center gap-2", children: [_jsx("span", { className: "text-xl", children: "+" }), " New Project"] }), _jsx("div", { className: "absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-200", style: { background: "linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)" } })] }), _jsx("button", { onClick: onOpenProjects, disabled: projects.length === 0, className: "group px-10 py-4 rounded-2xl text-lg font-semibold transition-all duration-200 disabled:opacity-30 disabled:cursor-not-allowed", style: { minWidth: 220, background: "rgba(255,255,255,0.05)", border: "1px solid rgba(139,92,246,0.4)", color: "#c5bedf", boxShadow: "0 4px 16px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.06)", backdropFilter: "blur(12px)" }, onMouseEnter: (e) => { if (projects.length > 0)
                                    e.currentTarget.style.borderColor = "rgba(139,92,246,0.8)"; }, onMouseLeave: (e) => { e.currentTarget.style.borderColor = "rgba(139,92,246,0.4)"; }, children: _jsxs("span", { className: "flex items-center justify-center gap-2", children: [_jsx("span", { children: "\u229E" }), " Open Project", projects.length > 0 && (_jsx("span", { className: "text-xs bg-[#7c3aed] text-white rounded-full px-2 py-0.5 ml-1", children: projects.length }))] }) })] })) : (_jsxs("div", { className: "flex flex-col items-center gap-4 p-8 rounded-2xl", style: { background: "rgba(20,17,42,0.85)", border: "1px solid rgba(139,92,246,0.4)", backdropFilter: "blur(20px)", boxShadow: "0 8px 40px rgba(0,0,0,0.6), 0 0 60px rgba(124,58,237,0.15)", minWidth: 360 }, children: [_jsx("p", { className: "text-sm font-semibold uppercase tracking-widest text-[#9b93ba]", children: "New Project" }), _jsx("input", { autoFocus: true, type: "text", placeholder: "Project name\u2026", value: projectName, onChange: (e) => setProjectName(e.target.value), onKeyDown: (e) => { if (e.key === "Enter")
                                    handleCreate(); if (e.key === "Escape") {
                                    setNaming(false);
                                    setProjectName("");
                                } }, className: "w-full text-center text-xl font-semibold text-white bg-transparent border-b-2 border-[#7c3aed] outline-none pb-2 placeholder:text-[#3a3456] caret-[#a78bfa]" }), _jsxs("div", { className: "flex gap-3 pt-1", children: [_jsx("button", { onClick: handleCreate, className: "px-8 py-2.5 rounded-xl text-sm font-semibold text-white transition-colors", style: { background: "linear-gradient(135deg, #7c3aed, #5b21b6)", boxShadow: "0 0 16px rgba(124,58,237,0.4)" }, children: "Create" }), _jsx("button", { onClick: () => { setNaming(false); setProjectName(""); }, className: "px-8 py-2.5 rounded-xl text-sm font-semibold text-[#5c5575] hover:text-[#9b93ba] transition-colors", style: { background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }, children: "Cancel" })] })] }))] }), _jsx("div", { className: "absolute bottom-6 left-0 right-0 flex justify-center z-10", children: _jsxs("p", { className: "text-xs text-[#3a3456] tracking-widest uppercase", children: ["Soul Assembly \u00B7 ", new Date().getFullYear()] }) })] }));
}
